event_query:
  - text: there is ${event_type} ${event_location}
    code: |
      ${event_type}
      ${event_location}
      events = Events.find_events(location=${event_location:var}, event_type=${event_type:var})
      test_events = len(events) > 0
    var: test_events
    type: query

event_location:
  - text: ${in_location}
    code: ${in_location}
    var: location

event_type:
  - text: ${event_type_item}
    code: |
      ${event_type:var} = EventType.resolve_from_text("${event_type_item}")
    var: event_type
    type: event_type

event_type_item:
  - ${concert}
  - ${show}
  - ${game}
  - ${personal_event}
  - ${work_event}

personal_event:
  - ${any|a} graduation ceremony
  - ${any|an} anniversary dinner
  - ${any|an} anniversary party
  - ${any|an} anniversary
  - ${any|a} birthday party
  - ${any|a} birthday
  - ${name}'s birthday
  - ${name}'s birthday party
  - ${any|a} dinner party
  - ${any|a} dinner
  - ${any|a} party
  - ${any|a} wedding ceremony
  - ${any|a} wedding reception
  - ${any|a} wedding
  - ${any|a} graduation
  - ${any|a} graduation party
  - ${any|a} graduation ceremony
  - ${any|a} graduation dinner
  - ${any|a} movie
  - ${any|a} movie night

work_event:
  - ${any|a} meeting
  - ${any|a} conference
  - ${any|a} conference call
  - ${any|a} conference meeting

show:
  - ${show_genre} event

show_genre:
  - ${any|a} standup comedy
  - ${any|a} comedy
  - ${any|a} comedy show
  - ${any|a} comedy

concert:
  - ${music_genre} ${event|concert|show}
  - ${any|a} ${performer} ${concert|show|event}

music_genre:
  - ${any|an} heavy metal
  - ${any|a} rock
  - ${any|a} pop
  - ${any|a} country
  - ${any|a} jazz
  - ${any|a} classical

game:
  - ${any|a} ${game_sport} ${game|match|tournament}

game_sport:
  - football
  - NFL
  - NBA
  - baseball
  - soccer
  - hockey
  - basketball
  - tennis
  - golf
  - cricket
  - rugby

performer:
  - Rihana
  - Beyonce
  - Ed Sheeran
  - Taylor Swift
  - Justin Bieber
  - Drake
  - Bruno Mars
  - Ariana Grande
  - Katy Perry
  - Lady Gaga
  - Maroon 5
  - The Weeknd
  - Coldplay
  - Miley Cyrus
  - Selena Gomez
  - Justin Timberlake
  - Nicki Minaj
  - One Direction
  - Adele
  - Rihanna
  - Eminem
  - Taylor Swift
  - Kanye West
  - Shakira
  - Jennifer Lopez
  - Pitbull
  - Enrique Iglesias
  - Bruno Mars
