utterance:
  # - ${condition}
  # - ${sequence}
  # - ${simple}
  - ${navigation_command_directions}

simple:
  - ${command}

command:
  - ${calendar_command}
  - ${home_command}
  - ${messages_command}
  - ${music_command}
  - ${navigation_command}
  - ${products_command}
  - ${reminders_command}
  - ${weather_command}
