to_location:
  - text: to ${location}
    code: ${location}
    var: location
    syn: PP

from_location:
  - text: from ${location}
    code: ${location}
    var: location
    syn: PP

at_location:
  - text: at ${location}
    code: ${location}
    var: location
    syn: PP

in_location:
  - text: in ${location}
    code: ${location}
    var: location
    syn: PP

near_location:
  - text: near ${location_landmark}
    code: |
      ${near_location:var} = Location.resolve_from_text("${location_landmark}")
    var: location
    syn: PP

on_location:
  - text: on ${on_location_item}
    code: |
      ${on_location:var} = Location.resolve_from_text("${on_location_item}")
    var: location
    type: location
    syn:
      num: sg
      label: PP
    coreference_value:
      - value: there

location_proximity:
  - text: ${location_proximity_item}
    code: |
      ${location_proximity:var} = Location.resolve_from_text("${location_proximity_item}")
    var: location
    type: location
    syn: PP

location:
  - text: ${location_exact}
    code: |
      ${location:var} = Location.resolve_from_text("${location_exact}")
    var: location
    syn: NN
    type: location
    coreference_value:
      - value: there

location_proximity_item:
  - near ${location_exact}

location_exact:
  - ${location_general}
  - ${location_relative}
  - text: ${location_landmark}
    code: ${location_landmark}
    weight: 0.1

location_exact_micro:
  - ${location_street_address}
  - text: ${location_landmark}
    code: ${location_landmark}
    weight: 0.1

location_general:
  - ${faker_country}
  - ${faker_city}
  - ${faker_street_name}

location_relative:
  - my neighborhood
  - my parents neighborhood
  - my work place
  - my office

location_landmark:
  - the airport
  - the boulevard
  - the city center
  - the harbor
  - the lake
  - the ${faker_brand} store
  - the mall
  - the stadium
  - the theater
  - the YMCA
  - the museum
  - the zoo
  - the ${faker_brand} building
  - the ${faker_brand} office
  - the ${faker_brand} headquarters
  - the ${faker_brand} factory
  - the ${faker_brand} warehouse
  - the ${faker_brand} plant


on_location_item:
  - ${faker_street_name} road
  - ${faker_street_name} street
  - ${faker_street_name} avenue

location_path:
  - text: ${location_path_item}
    code: |
      ${location_path_item:var} = Location.resolve_from_text("${location_path_item}")
    var: location
    type: location

location_path_item:
  - text: highway ${faker_digit}
    code: "highway ${faker_digit}"
  - text: highway ${faker_two_digits}
    code: "highway ${faker_two_digits}"
  - text: hwy ${faker_digit}
    code: "hwy ${faker_digit}"
  - text: hwy ${faker_two_digits}
    code: "hwy ${faker_two_digits}"
  - text: I-${faker_digit}
    code: "I-${faker_digit}"
  - text: I-${faker_two_digits}
    code: "I-${faker_two_digits}"
  - text: Route ${faker_two_digits}
    code: "Route ${faker_two_digits}"
  - text: the freeway
    code: "the freeway"
  - text: the highway
    code: "the highway"
  - text: the tollroad
    code: "the tollroad"
