messages_command:
  - ${simple_message_command}
  - ${loop_message_command}

simple_message_command:
  - text: ${message_verb} ${recipient} ${message_exact_content}
    code: |
      ${recipient}
      ${message_exact_content}
      Message.send_message(recipient=${recipient:var}, exact_content=${message_exact_content:var})

loop_message_command:
  - text: ${message_verb} ${recipient.1} and ${recipient.2} ${message_exact_content}
    code: |
      ${recipient.1}
      ${recipient.2}
      for recipient in [${recipient.1:var}, ${recipient.2:var}]:
        ${message_exact_content}
        Message.send_message(recipient=recipient, exact_content=${message_exact_content:var})
  - text: ${message_verb} ${recipient.1}, ${recipient.2} and ${recipient.3} ${message_exact_content}
    code: |
      ${recipient.1}
      ${recipient.2}
      ${recipient.3}
      for recipient in [${recipient.1:var}, ${recipient.2:var}, ${recipient.3:var}]:
        ${message_exact_content}
        Message.send_message(recipient=recipient, exact_content=${message_exact_content:var})
  - text: ${message_verb} ${recipients} ${message_exact_content}
    code: |
      ${recipients}
      for recipient in ${recipients:var}:
        ${message_exact_content}
        Message.send_message(recipient=recipient, exact_content=${message_exact_content:var})
  - text: ${message_verb} ${recipient.1} and ${recipients} ${message_exact_content}
    code: |
      ${recipient.1}
      ${recipients}
      for recipient in ${recipients:var} + [${recipient.1:var}]:
        ${message_exact_content}
        Message.send_message(recipient=recipient, exact_content=${message_exact_content:var})

messages_query:
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender}
    code: |
      ${contact_i}
      ${sender}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var})
      result = len(messages) > 0
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender} {past_date_time}
    code: |
      ${contact_i}
      ${sender}
      ${past_date_time}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var}, date_time=${past_date_time:var})
      result = len(messages) > 0
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2}
    code: |
      ${contact_i}
      recipient = ${contact_i:var}
      ${sender.1}
      ${sender.2}
      result = True
      for sender in [${sender.1:var}, ${sender.2:var}]:
        messages = Message.find_messages(recipient=recipient, sender=sender)
        result = result and len(messages) > 0
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2} {past_date_time}
    code: |
      ${contact_i}
      ${sender.1}
      ${sender.2}
      ${past_date_time}
      result = True
      for sender in [${sender.1:var}, ${sender.2:var}]:
        messages = Message.find_messages(date_time=${past_date_time:var}, recipient=recipient, sender=sender)
        result = result and len(messages) > 0
    var: result

message_verb:
  - text
  - email
  - message

messages_possession_verb:
  - have
  - got

sender:
  - ${contact}

recipient:
  - text: ${contact}
    code: ${contact}
    var: recipient

recipients:
  - text: ${contacts}
    code: ${contacts}
    var: recipients

message_exact_content:
  - text: ${message_content_item}
    code: |
      ${message_exact_content:var} = Content.resolve_from_text("${message_content_item}")
    var: exact_content

message_content_item:
  - text: to meet us inside the restaurant
    code: "meet us inside the restaurant"
  - text: that I will be on time
    code: "I will be on time"
  - text: that I will be late
    code: "I will be late"
  - text: that I will be there in 10 minutes
    code: "I will be there in 10 minutes"
  - text: "and let ${recipient} know that I will be there in 10 minutes"
    code: "I will be there in 10 minutes"
  - text: to tell ${recipient} that I'll be out of the office for the next two hours.
    code: "I'll be out of the office for the next two hours."
  - text: "to see if ${recipient[{'syn': {'form': 'subj'}}]} is there"
    code: "see if ${recipient[{'syn': {'form': 'subj'}}]:text} is there"
  - text: and ask ${recipient} to meet for coffee
    code: "meet for coffee"
