messages_query:
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${sender}
    code: |
      ${contact_i}
      ${sender}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${sender} ${past_date_time}
    code: |
      ${contact_i}
      ${sender}
      ${past_date_time}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var}, date_time=${past_date_time:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: quer
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${senders}
    code: |
      ${contact_i}
      ${senders}
      messages = []
      for sender in ${senders:var}:
        messages += Message.find_messages(recipient=${contact_i:var}, sender=sender)
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${senders} ${past_date_time}
    code: |
      ${contact_i}
      ${senders}
      ${past_date_time}
      messages = []
      for sender in ${senders:var}:
        messages += Message.find_messages(date_time=${past_date_time:var}, recipient=${contact_i:var}, sender=sender)
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${sender} ${past_date_times}
    code: |
      ${contact_i}
      ${sender}
      ${past_date_times}
      messages = []
      for date_time in ${past_date_times:var}:
        messages += Message.find_messages(date_time=date_time, recipient=${contact_i:var}, sender=${sender:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${senders} ${past_date_times}
    code: |
      ${contact_i}
      ${senders}
      ${past_date_times}
      messages = []
      for sender in ${senders:var}:
        for date_time in ${past_date_times:var}:
          messages += Message.find_messages(date_time=date_time, recipient=${contact_i:var}, sender=sender)
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} from ${sender} ${that|which} includes ${message_content_attachment}
    code: |
      ${contact_i}
      ${sender}
      ${message_content_attachment}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var}, content=${message_content_attachment:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${a message|an email} ${that|which} includes ${message_content_attachment}
    code: |
      ${contact_i}
      ${message_content_attachment}
      messages = Message.find_messages(recipient=${contact_i:var}, content=${message_content_attachment:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${message_content_attachment} from ${sender}
    code: |
      ${contact_i}
      ${message_content_attachment}
      ${sender}
      messages = Message.find_messages(recipient=${contact_i:var}, sender=${sender:var}, content=${message_content_attachment:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
  - text: ${contact_i} ${messages_possession_verb} ${message_content_attachment}
    code: |
      ${contact_i}
      ${message_content_attachment}
      messages = Message.find_messages(recipient=${contact_i:var}, content=${message_content_attachment:var})
      ${messages_query:var} = bool(messages)
    var: test_messages
    type: query
