products_query:
  - text: ${product_name} are ${product_attribute_suffix}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      products = Product.find_products(product=${product:var}, product_attribute=${product_attribute_suffix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_name} are ${product_attribute_suffix} at ${store}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      ${store}
      products = Product.find_products(product=${product:var}, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_name} are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      ${stores}
      products = []
      for location in ${stores:var}:
        products += Product.find_products(product=${product:var}, product_attribute=${product_attribute_suffix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_name.1} are ${product_attribute_suffix} ${cc} ${product_name.2} are ${product_attribute_suffix}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_name.1} are ${product_attribute_suffix} ${cc} ${product_name.2} are ${product_attribute_suffix} at ${store}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      ${store}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_name.1} are ${product_attribute_suffix} ${cc} ${product_name.2} are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      ${stores}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        for store in ${stores:var}:
          products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_names} are ${product_attribute_suffix}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      products = []
      for product_name in ${product_names:var}:
        products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_names} are ${product_attribute_suffix} at ${store}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      ${store}
      products = []
      for product_name in ${product_names:var}:
        products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${product_names} are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      ${stores}
      products = []
      for product_name in ${product_names:var}:
        for location in ${stores:var}:
          products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_name}
    code: |
      ${product_name}
      ${product_attribute_prefix}
      products = Product.find_products(product=${product:var}, product_attribute=${product_attribute_prefix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_names}
    code: |
      ${product_attribute_prefix}
      ${product_names}
      products = []
      for product_name in ${product_names:var}:
        products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_name} at ${store}
    code: |
      ${product_name}
      ${product_attribute_prefix}
      ${store}
      products = Product.find_products(product=${product:var}, product_attribute=${product_attribute_prefix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2} at ${store}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      ${store}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2} at ${stores}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      ${stores}
      products = []
      for product in [${product_name.1:var}, ${product_name.2:var}]:
        for location in ${stores:var}:
          products = products ${cc} Product.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: there is ${product_attribute_prefix} on ${product_names} at ${stores}
    code: |
      ${product_attribute_prefix}
      ${product_names}
      ${stores}
      products = []
      for product_name in ${product_names:var}:
        for location in ${stores:var}:
          products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${store} has ${product_name} ${product_attribute_suffix}
    code: |
      ${store}
      ${product_name}
      ${product_attribute_suffix}
      products = Product.find_products(product=${product:var}, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${stores} have ${product_name} ${product_attribute_suffix}
    code: |
      ${stores}
      ${product_name}
      ${product_attribute_suffix}
      products = []
      for location in ${stores:var}:
        products += Product.find_products(product=${product:var}, product_attribute=${product_attribute_suffix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${store} has ${product_names} ${product_attribute_suffix}
    code: |
      ${store}
      ${product_names}
      ${product_attribute_suffix}
      products = []
      for product_name in ${product_names:var}:
        products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
      ${products_query:var} = bool(products)
    var: test_products
    type: query
  - text: ${stores} have ${product_names} ${product_attribute_suffix}
    code: |
      ${stores}
      ${product_names}
      ${product_attribute_suffix}
      products = []
      for location in ${stores:var}:
        for product_name in ${product_names:var}:
          products += Product.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=location)
      ${products_query:var} = bool(products)
    var: test_products
    type: query
