weather_condition:
  - text: it ${weather_condition_term}
    code: |
      ${weather_condition:var} = WeatherCondition.resolve_from_text("${weather_condition_term}")
    var: weather_condition
    syn:
      label: VP
  - text: it is expected to be ${weather_condition_gerund_term}
    code: |
      ${weather_condition:var} = WeatherCondition.resolve_from_text("${weather_condition_term}")
    var: weather_condition
    syn:
      label: VP

weather_conditions:
  - text: it ${weather_condition_terms}
    code: |
      ${weather_conditions:var} = WeatherCondition.resolve_many_from_text("${weather_condition_terms}")
    var: weather_conditions
    syn:
      label: VP
  - text: it ${weather_condition_gerund_terms}
    code: |
      ${weather_conditions:var} = WeatherCondition.resolve_many_from_text("${weather_condition_gerund_terms}")
    var: weather_conditions
    syn:
      label: VP

weather_condition_term:
  - rains
  - snows
  - freezes
  - hails
  - sleets
  - drizzles
  - pours
  - will be sunny
  - will be nice
  - will be warm
  - will be cold
  - will be chilly
  - will be hot
  - will be cool
  - will be breezy
  - will be stormy
  - will be thundering
  - will be lightning
  - will be hazy
  - will be smoggy
  - will be dusty
  - will be foggy
  - will be cloudy
  - will be humid
  - will be dry
  - will be windy

weather_condition_terms:
  - ${weather_condition_term.1} ${cc} ${weather_condition_term.2}

weather_condition_gerund_term:
  - raining
  - snowing
  - freezing
  - nice
  - warm
  - sunny
  - windy
  - foggy
  - cloudy
  - chilly
  - humid
  - dry
  - hot
  - cold
  - cool
  - breezy
  - stormy
  - hailing
  - sleeting
  - drizzling
  - pouring
  - misting
  - sprinkling
  - blizzarding
  - thundering
  - lightning
  - hazy
  - smoggy
  - dusty

weather_condition_gerund_terms:
  - ${weather_condition_gerund_term.1} ${cc} ${weather_condition_gerund_term.2}

weather_location:
  - text: ${at_location}
    code: ${at_location}
    var: location
    weight: 0.25
  - text: ${in_location}
    code: ${in_location}
    var: location
  - text: ${on_location}
    code: ${on_location}
    var: location
    weight: 0.25

weather_locations:
  - text: ${at_locations}
    code: ${at_locations}
    var: location
    weight: 0.25
  - text: ${in_locations}
    code: ${in_locations}
    var: location
  - text: ${on_locations}
    code: ${on_locations}
    var: location
    weight: 0.25

weather_date_time:
  - text: ${at_date_time}
    code: ${at_date_time}
    var: date_time
    type: date_time
    coreference_value:
      - value: at that time
  - text: ${on_date_time}
    code: ${on_date_time}
    var: date_time
    type: date_time
    coreference_value:
      - value: at that time
  - text: ${now_date_time}
    code: ${now_date_time}
    var: date_time
    type: date_time
    coreference_value:
      - value: at that time
    weight: 0.25

weather_date_times:
  - text: ${every_date_times}
    code: ${every_date_times}
    var: date_times
    coreference_value:
      - value: at that time
  - text: ${on_date_times}
    code: ${on_date_times}
    var: date_times
    coreference_value:
      - value: at that time
