calendar_command:
  - ${calendar_command_query}
  - ${calendar_command_schedule}
  - ${calendar_command_query_tickets}

calendar_command_query:
  - text: ${query_command_verb} if ${events_query}
    code: |
      ${events_query}
      Responder.respond(response=${events_query:var})
    var: ${events_query:var}
  - text: ${query_command_verb} if ${calendar_command_query_tickets_item}
    code: |
      ${calendar_command_query_tickets_item}
      Responder.respond(response=${calendar_command_query_tickets_item:var})
    var: ${calendar_command_query_tickets_item:var}

calendar_command_schedule:
  - text: ${schedule_command_action} ${event_name}
    code: |
      ${event_name}
      Calendar.schedule_event(event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_date_time} ${event_name}
    code: |
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      Calendar.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_date_time}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_date_time} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_action} ${event_name} ${event_calendar}
    code: |
      ${event_name}
      ${event_calendar}
      Calendar.schedule_event(event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${event_name} ${event_date_time} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${event_date_time} ${event_name} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_calendar} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_calendar}
      Calendar.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_name} ${event_date_time} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_action} ${in|on} ${event_calendar} ${event_date_time} ${event_name} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Calendar.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})

events_command_ticket_purchase:
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name}
    code: |
      ${event_name}
      events = Calendar.find_events(event_name=${event_name:var})
      ${event_ticket_amount}
      Calendar.purchase_ticket(events=events, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      events = Calendar.find_events(date_time={event_date_time:var}, event_name=${event_name:var})
      ${event_ticket_amount}
      Calendar.purchase_ticket(events=events, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      events = Calendar.find_events(event_name=${event_name:var}, location=${event_location:var})
      ${event_ticket_amount}
      Calendar.purchase_ticket(events=events, amount=${event_ticket_amount:var})
  - text: ${calendar_purchase_action} ${event_ticket_amount} tickets for the ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_location}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      ${event_ticket_amount}
      Calendar.purchase_ticket(events=events, amount=${event_ticket_amount:var})

calendar_command_query_tickets:
  - text: ${query_command_verb} if ${calendar_command_query_tickets_item}
    code: |
      ${calendar_command_query_tickets_item}
    var: ${calendar_command_query_tickets_item:var}

calendar_command_query_tickets_item:
  - text: there are tickets for ${event_name}
    code: |
      ${event_name}
      events = Calendar.find_events(event_name=${event_name:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      events = Calendar.find_events(event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location} ${event_date_time}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name}
    code: |
      ${event_name}
      events = Calendar.find_events(event_name=${event_name:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      events = Calendar.find_events(event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_location} ${event_date_time}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets
  - text: there are tickets for ${event_name} ${event_date_time} ${event_location}
    code: |
      ${event_name}
      ${event_location}
      ${event_date_time}
      events = Calendar.find_events(date_time=${event_date_time:var}, event_name=${event_name:var}, location=${event_location:var})
      ${calendar_command_query_tickets:var} = Calendar.find_events_tickets(events=events)
    var: event_tickets

schedule_command_action:
  - create ${an entry|a new entry}
  - schedule ${an entry|a new entry}
  - set ${an entry|a new entry}

calendar_purchase_action:
  - buy
  - purchase
  - get
  - reserve
