events_command:
  - ${events_command_query}

events_command_query:
  - text: ${query_command_verb} if ${events_query}
    code: |
      ${events_query}
      Responder.respond(response=${events_query:var})
    var: ${events_query:var}

events_schedule_event_command:
  - text: ${schedule_command_verb} ${event_name}
    code: |
      ${event_name}
      Event.schedule_event(event_name=${event_name:var})
  - text: ${schedule_command_verb} ${event_name} ${event_date_time}
    code: |
      ${event_name}
      ${event_date_time}
      Event.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_verb} ${event_date_time} ${event_name}
    code: |
      ${event_name}
      ${event_date_time}
      Event.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      Event.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_name} ${event_date_time}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Event.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_date_time} ${event_name}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      Event.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var})
  - text: ${schedule_command_verb} ${event_name} ${event_calendar}
    code: |
      ${event_name}
      ${event_calendar}
      Event.schedule_event(event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_verb} ${event_name} ${event_date_time} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Event.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_verb} ${event_date_time} ${event_name} ${event_calendar}
    code: |
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Event.schedule_event(date_time=${event_date_time:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_name} ${event_calendar} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_calendar}
      Event.schedule_event(event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_name} ${event_date_time} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Event.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})
  - text: ${schedule_command_verb} ${in|on} ${event_calendar} ${event_date_time} ${event_name} ${event_calendar}
    code: |
      ${event_calendar}
      ${event_name}
      ${event_date_time}
      ${event_calendar}
      Event.schedule_event(date_time=${event_date_time:var}, event_calendar=${event_calendar:var}, event_name=${event_name:var}, event_calendar=${event_calendar:var})

schedule_command_verb:
  - create ${an entry|a new entry}
  - schedule ${an entry|a new entry}
  - set ${an entry|a new entry}
