reminders_command:
  - ${reminders_command_query}
  - ${reminders_command_create}
  - ${reminders_command_delete}

reminders_command_query:
  - text: ${query_command_verb} if ${reminders_query}
    code: |
      ${reminders_query}
      Responder.respond(response=${reminders_query:var})
    var: ${reminders_query:var}

reminders_command_create:
  - text: ${reminder_create_action} ${reminder_exact_content}
    code: |
      ${reminder_exact_content}
      Reminder.create_reminder(exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_exact_content}
    code: |
      ${person_reminded_me}
      ${reminder_exact_content}
      Reminder.create_reminder(person_reminded=${person_reminded_me:var}, exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${reminder_date_time} ${reminder_exact_content}
    code: |
      ${reminder_date_time}
      ${reminder_exact_content}
      Reminder.create_reminder(date_time=${reminder_date_time:var}, exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_date_time} ${reminder_exact_content}
    code: |
      ${reminder_date_time}
      ${person_reminded_me}
      ${reminder_exact_content}
      Reminder.create_reminder(date_time=${reminder_date_time:var}, person_reminded=${person_reminded_me:var}, exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${reminder_date_times} ${reminder_exact_content}
    code: |
      ${reminder_date_times}
      ${reminder_exact_content}
      for date_time in ${reminder_date_times:var}:
        Reminder.create_reminder(date_time=date_time, exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_date_times} ${reminder_exact_content}
    code: |
      ${reminder_date_times}
      ${person_reminded_me}
      ${reminder_exact_content}
      for date_time in ${reminder_date_times:var}:
        Reminder.create_reminder(date_time=date_time, person_reminded=${person_reminded_me:var}, exact_content=${reminder_exact_content:var})
  - text: ${reminder_create_action} ${reminder_exact_contents
    code: |
      ${reminder_exact_contents}
      for exact_content in [${reminder_exact_contents:var}]:
        Reminder.create_reminder(exact_content=exact_content)
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_exact_contents}
    code: |
      ${person_reminded_me}
      ${reminder_exact_contents}
      for exact_content in [${reminder_exact_contents:var}]:
        Reminder.create_reminder(person_reminded=${person_reminded_me:var}, exact_content=exact_content)
  - text: ${reminder_create_action} ${reminder_date_time} ${reminder_exact_contents}
    code: |
      ${reminder_date_time}
      ${reminder_exact_contents}
      for exact_content in [${reminder_exact_contents:var}]:
        Reminder.create_reminder(date_time=${reminder_date_time:var}, exact_content=exact_content)
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_date_time} ${reminder_exact_content}
    code: |
      ${reminder_date_time}
      ${person_reminded_me}
      ${reminder_exact_contents}
      for exact_content in [${reminder_exact_contents:var}]:
        for exact_content in [${reminder_exact_contents:var}]:
          Reminder.create_reminder(date_time=${reminder_date_time:var}, person_reminded=${person_reminded_me:var}, exact_content=exact_content)
  - text: ${reminder_create_action} ${reminder_date_times} ${reminder_exact_content}
    code: |
      ${reminder_date_times}
      ${reminder_exact_contents}
      for date_time in ${reminder_date_times:var}:
        for exact_content in [${reminder_exact_contents:var}]:
          Reminder.create_reminder(date_time=date_time, exact_content=exact_content)
  - text: ${reminder_create_action} ${person_reminded_me} ${reminder_date_times} ${reminder_exact_content}
    code: |
      ${reminder_date_times}
      ${person_reminded_me}
      ${reminder_exact_contents}
      for exact_content in [${reminder_exact_contents:var}]:
        for date_time in ${reminder_date_times:var}:
          Reminder.create_reminder(date_time=date_time, person_reminded=${person_reminded_me:var}, exact_content=exact_content)

reminders_command_delete:
  - text: ${reminder_delete_action} ${quantifier(reminders, det=the)} ${reminder_exact_content}
    code: |
      ${reminder_exact_content}
      reminders = Reminder.find_reminders(exact_content=${reminder_exact_content:var})
      reminders = ${quantifier(reminders, det=the)}
      Reminder.delete_reminder(reminders=reminders)
  - text: ${reminder_delete_action} ${quantifier(reminders, nmod_poss={person_reminded_my})} ${reminder_exact_content}
    code: |
      ${person_reminded_my}
      ${reminder_exact_content}
      reminders = Reminder.find_reminders(person_reminded=${person_reminded_my:var}, exact_content=${reminder_exact_content:var})
      reminders = ${quantifier(reminders, nmod_poss={person_reminded_my})}
      Reminder.delete_reminder(reminders=reminders)
  - text: ${reminder_delete_action} ${quantifier(reminders, det=the)} ${reminder_exact_contents}
    code: |
      ${reminder_exact_contents}
      all_reminders = []
      for exact_content in [${reminder_exact_contents:var}]:
        reminders = Reminder.find_reminders(exact_content=exact_content)
        reminders = ${quantifier(reminders, det=the)}
        all_reminders += reminders
      Reminder.delete_reminder(reminders=all_reminders)
  - text: ${reminder_delete_action} ${quantifier(reminders, nmod_poss={person_reminded_my})} ${reminder_exact_contents}
    code: |
      ${person_reminded_my}
      ${reminder_exact_contents}
      all_reminders = []
      for exact_content in [${reminder_exact_contents:var}]:
        reminders = Reminder.find_reminders(person_reminded=${person_reminded_my:var}, exact_content=exact_content)
        reminders = ${quantifier(reminders, nmod_poss={person_reminded_my})}
        all_reminders += reminders
      Reminder.delete_reminder(reminders=all_reminders)

reminder_create_action:
  - ${create|set} a reminder
  - remind

reminder_delete_action:
  - remove
  - delete
  - cancel
  - clear
  - erase
