products_command:
  - ${products_command_find}
  - ${products_command_shopping_list}

products_command_find:
  - text: ${products_find_action} ${products_comp_list}
    code: |
      ${products_comp_list}
      Responder.respond(response=${products_comp_list:var})
    var: ${products_comp_list:var}
  - text: ${products_find_action} ${products_xcomp_list}
    code: |
      ${products_xcomp_list}
      Responder.respond(response=${products_xcomp_list:var})
    var: ${products_xcomp_list:var}

products_command_query:
  - text: ${query_command_verb} if ${products_comp_list}
    code: |
      ${products_comp_list}
      Responder.respond(response=${products_comp_list:var})
    var: ${products_comp_list:var}

products_comp_list:
  - text: ${product_name} that are ${product_attribute_suffix}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      ${products_comp_list:var} = Shopping.find_products(product_name=${product_name:var}, product_attribute=${product_attribute_suffix:var})
    var: products
  - text: ${product_name} that are ${product_attribute_suffix} at ${store}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      ${store}
      ${products_comp_list:var} = Shopping.find_products(product_name=${product_name:var}, product_attribute=${product_attribute_suffix:var}, location=${store:var})
    var: products
  - text: ${product_name} that are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_name}
      ${product_attribute_suffix}
      ${stores}
      ${products_comp_list:var} = []
      for location in ${stores:var}:
        ${products_comp_list:var} += Shopping.find_products(product_name=${product_name:var}, product_attribute=${product_attribute_suffix:var}, location=location)
    var: products
  - text: ${product_name.1} that are ${product_attribute_suffix} ${cc} ${product_name.2} that are ${product_attribute_suffix}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      ${products_comp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var})
    var: products
  - text: ${product_name.1} that are ${product_attribute_suffix} ${cc} ${product_name.2} that are ${product_attribute_suffix} at ${store}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      ${store}
      ${products_comp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
    var: products
  - text: ${product_name.1} that are ${product_attribute_suffix} ${cc} ${product_name.2} that are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_name.1}
      ${product_name.2}
      ${product_attribute_suffix}
      ${stores}
      ${products_comp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        for location in ${stores:var}:
          ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=location)
    var: products
  - text: ${product_names} that are ${product_attribute_suffix}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      ${products_comp_list:var} = []
      for product_name in ${product_names:var}:
        ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var})
    var: products
  - text: ${product_names} that are ${product_attribute_suffix} at ${store}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      ${store}
      ${products_comp_list:var} = []
      for product_name in ${product_names:var}:
        ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=${store:var})
    var: products
  - text: ${product_names} that are ${product_attribute_suffix} at ${stores}
    code: |
      ${product_names}
      ${product_attribute_suffix}
      ${stores}
      ${products_comp_list:var} = []
      for product_name in ${product_names:var}:
        for location in ${stores:var}:
          ${products_comp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_suffix:var}, location=location)
    var: products

products_xcomp_list:
  - text: ${product_attribute_prefix} on ${product_name}
    code: |
      ${product_name}
      ${product_attribute_prefix}
      ${products_xcomp_list:var} = Shopping.find_products(product_name=${product_name:var}, product_attribute=${product_attribute_prefix:var})
    var: products
  - text: ${product_attribute_prefix} on ${product_names}
    code: |
      ${product_attribute_prefix}
      ${product_names}
      ${products_xcomp_list:var} = []
      for product_name in ${product_names:var}:
        ${products_xcomp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var})
    var: products
  - text: ${product_attribute_prefix} on ${product_name} at ${store}
    code: |
      ${product_name}
      ${product_attribute_prefix}
      ${store}
      ${products_xcomp_list:var} = Shopping.find_products(product_name=${product_name:var}, product_attribute=${product_attribute_prefix:var}, location=${store:var})
    var: products
  - text: ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      ${products_xcomp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        ${products_xcomp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var})
    var: products
  - text: ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2} at ${store}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      ${store}
      ${products_xcomp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        ${products_xcomp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=${store:var})
    var: products
  - text: ${product_attribute_prefix} on ${product_name.1} ${cc} ${product_attribute_prefix} on ${product_name.2} at ${stores}
    code: |
      ${product_attribute_prefix}
      ${product_name.1}
      ${product_name.2}
      ${stores}
      ${products_xcomp_list:var} = []
      for product_name in [${product_name.1:var}, ${product_name.2:var}]:
        for location in ${stores:var}:
          ${products_xcomp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=location)
    var: products
  - text: ${product_attribute_prefix} on ${product_names} at ${stores}
    code: |
      ${product_attribute_prefix}
      ${product_names}
      ${stores}
      ${products_xcomp_list:var} = []
      for product_name in ${product_names:var}:
        for location in ${stores:var}:
          ${products_xcomp_list:var} += Shopping.find_products(product_name=product_name, product_attribute=${product_attribute_prefix:var}, location=location)
    var: products

products_command_shopping_list:
  - text: add ${product_name} to ${shopping_list_name}
    code: |
      ${product_name}
      ${shopping_list_name}
      ${products_command_shopping_list:var} = Shopping.add_to_shopping_list(product_name=${product_name:var}, shopping_list_name=${shopping_list_name:var})
    var: shopping_list
  - text: add ${product_names} to ${shopping_list_name}
    code: |
      ${product_names}
      ${shopping_list_name}
      for product_name in ${product_names:var}:
        ${products_command_shopping_list:var} = Shopping.add_to_shopping_list(product_name=product_name, shopping_list_name=${shopping_list_name:var})
    var: shopping_list

products_find_action:
  - check for
  - show me
  - find
  - list
  - search
  - look for
