contact:
  - text: ${name}
    code: |
      ${contact:var} = Contact.resolve_from_text("${name}")
    var: contact

contact_me:
  - text: me
    code: |
      ${contact_me:var} = Contact.resolve_from_text("me")
    var: contact

contact_my:
  - text: my
    code: |
      ${contact_my:var} = Contact.resolve_from_text("my")
    var: contact

contact_i:
  - text: I
    code: |
      ${contact_i:var} = Contact.resolve_from_text("I")
    var: contact

name:
  - ${full_name_male}
  - ${first_name_male}
  - ${full_name_female}
  - ${first_name_female}

full_name_male:
  - text: ${first_name_male} ${faker_last_name}
    code: ${faker_first_name_male} ${faker_last_name}
    syn:
      gend: masc
      num: sg

full_name_female:
  - text: ${faker_first_name_female} ${faker_last_name}
    code: ${faker_first_name_female} ${faker_last_name}
    syn:
      gend: fem
      num: sg

first_name_male:
  - text: ${faker_first_name_male}
    code: ${faker_first_name_male}
    syn:
      gend: masc
      num: sg

first_name_female:
  - text: ${faker_first_name_female}
    code: ${faker_first_name_female}
    syn:  
      gend: fem
      num: sg
