contact:
  - text: ${name}
    code: |
      ${contact:var} = Contact.resolve_from_text("${name}")
    var: contact
contact_me:
  - text: me
    code: |
      ${contact_me:var} = Contact.resolve_from_text("me")
    var: contact
contact_my:
  - text: my
    code: |
      ${contact_my:var} = Contact.resolve_from_text("my")
    var: contact
contact_i:
  - text: I
    code: |
      ${contact_i:var} = Contact.resolve_from_text("I")
    var: contact
name:
  - ${faker_name}
  - ${faker_first_name}
name_male:
  - text: ${faker_first_name_male}
    code: ${faker_first_name_male}
    gend: masc
    num: sg
name_female:
  - text: ${faker_first_name_female}
    code: ${faker_first_name_female}
    gend: fem
    num: sg
