at_date_time:
  - text: at ${date_time_exact}
    code: ${date_time_exact}
    var: date_time
    syn: pp

for_date_time:
  - text: for ${date_time_relative}
    code: ${date_time_relative}
    var: date_time
    syn: pp

on_date_time:
  - text: on ${date_time_general}
    code: ${date_time_general}
    var: date_time
    syn: pp

date_time:
  - text: ${date_time_relative}
    code: ${date_time_relative}
    var: date_time
  - text: ${date_time_general}
    code: ${date_time_general}
    var: date_time
  - text: ${date_time_exact}
    code: ${date_time_exact}
    var: date_time

date_time_relative:
  - text: ${date_time_relative_item}
    code: ${date_time_relative:var} = DateTime.resolve_from_text("${date_time_relative_item}")
    var: date_time
    type: date_time
    syn: NP

date_time_general:
  - text: ${date_time_general_item}
    code: ${date_time_general:var} = DateTime.resolve_from_text("${date_time_general_item}")
    var: date_time
    type: date_time
    syn: NP

date_time_exact:
  - text: ${date_time_exact_item}
    code: ${date_time_exact:var} = DateTime.resolve_from_text("${date_time_exact_item}")
    var: date_time
    type: date_time
    syn: NP

date_time_now:
  - text: ${date_time_now_item}
    code: ${date_time_now:var} = DateTime.resolve_from_text("${date_time_now_item}")
    var: date_time
    type: date_time
    syn: NP

date_time_past:
  - text: ${date_time_past_term}
    code: ${date_time_past:var} = DateTime.resolve_from_text("${date_time_past_term}")
    var: date_time
    type: date_time
    syn: NP

date_time_relative_item:
  - today
  - tonight
  - tomorrow
  - tomorrow ${times_of_day}
  - the day after tomorrow
  - the ${times_of_day} of the day after tomorrow
  - the weekend
  - ${day_of_week} ${times_of_day}

date_time_general_item:
  - ${day_of_week}

date_time_now_item:
  - now
  - right now
  - at this moment

date_time_exact_item:
  - ${date_time_hour}
  - noon
  - midnight

month_name:
  - ${faker_month_name}

date_time_hour:
  - ${date_time_hour_term}
  - ${date_time_hour_term} ${date_time_future}
  # - text: ${date_time_future} at ${date_time_hour_term}
  #   code: "${date_time_future} at ${date_time_hour_term}"

date_time_future:
  - tomorrow
  - next week
  - next month
  - the day after tomorrow
  - in 2 days

date_time_hour_term:
  - ${faker_time_hour}
  - ${faker_time_hour_minutes}
  - mindnight
  - noon
  # - at ${faker_time_hour} am tomorrow morning
  # - tomorrow morning at ${faker_time_hour} am
  # - at ${faker_time_hour} pm tonight
  # - tonight at ${faker_time_hour} pm

date_time_past_term:
  - today
  - yesterday
  - ${date_time_hour_term}

day_of_week:
  - ${faker_day_of_week}

times_of_day:
  - morning
  - afternoon
  - evening
  - night
