cc:
  - text: and
    code: and
    format: False
  - text: or
    code: or
    format: False

neg:
  - text: not
    code: not
    weight: 0.1

quantifier\((.+)\):
  # quantifier:
  - text: all $nmod:poss $obj
    code: |
      $var
  - text: $nmod:poss $det first $obj
    code: |
      first($var)
    num: 'sg'
  - text: $nmod:poss $det first ${numbers} $var
    code: |
      first($var, ${numbers})
  - text: $nmod:poss $det last $obj
    code: |
      last($var)
    num: 'sg'
  - text: $nmod:poss $det last ${numbers} $obj
    code: |
      last($var, ${numbers})

numbers:
  - text: two
    code: 2
  - text: three
    code: 3
