utterance:
  # - ${condition}
  # - ${sequence}
  - ${complex}

complex:
  - ${command}

command:
  # - ${messages_command}
  # - ${navigation_command}
  - ${reminders_command}
  # - ${weather_command}

query:
  - ${weather_query}
  - ${navigation_traffic_query}

sequence:
  - text: after you ${command.1}, ${command.2}
    code: |
      ${command.1}

      ${command.2}
    weight: 0.3
  - text: before you ${command.1}, ${command.2}
    code: |
      ${command.2}

      ${command.1}
    weight: 0.3
  - text: ${command.1} and ${command.2}
    code: |
      ${command.1}

      ${command.2}
    weight: 0.1
  - text: ${sequence}, ${command.1} and ${command.2}
    code: |
      ${sequence}

      ${command.1}

      ${command.2}
    weight: 0.05
