utterance:
  # - ${condition}
  - ${sequence}
  # - ${simple}

simple:
  - ${command}

command:
  - ${messages_command}
  - ${navigation_command}
  - ${reminders_command}
  - ${weather_command}

query:
  - ${weather_query}
  - text: ${navigation_traffic_query}
    code: ${navigation_traffic_query}
    var: ${navigation_traffic_query:var}
  # - ${navigation_estimate_arrival_query}
  # - ${navigation_estimate_departure_query}
