location:
  - text: ${location_sing}
    code: ${location_sing}
    var: location #${location_sing:var}

location_sing:
  - text: ${specific_location}
    code: |
      ${location_sing:var} = Location.resolve_from_text("${specific_location}")

specific_location:
  - ${faker_city}
  - ${faker_country}
  - ${faker_street_name}

location_landmark:
  - text: ${location_landmark_item}
    code: |
      ${location_landmark_item:var} = Location.resolve_from_text(${location_landmark_item})
    var: ${location_landmark_item:var}

location_landmark_item:
  - the airport
  - the boulevard
  - the city center
  - the harbor
  - the lake
  - the ${faker_brand} store
  - the mall
  - the stadium
  - the theater
  - the YMCA

location_path:
  - text: ${location_path_item}
    code: |
      ${location_path_item:var} = Location.resolve_from_text(${location_path_item})
    var: ${location_path_item:var}

location_path_item:
  - text: highway ${faker_digit}
    code: "highway ${faker_digit}"
  - text: highway ${faker_two_digits}
    code: "highway ${faker_two_digits}"
  - text: hwy ${faker_digit}
    code: "hwy ${faker_digit}"
  - text: hwy ${faker_two_digits}
    code: "hwy ${faker_two_digits}"
  - text: I-${faker_digit}
    code: "I-${faker_digit}"
  - text: I-${faker_two_digits}
    code: "I-${faker_two_digits}"
  - text: Route ${faker_two_digits}
    code: "Route ${faker_two_digits}"
  - text: the freeway
    code: "the freeway"
  - text: the highway
    code: "the highway"
  - text: the tollroad
    code: "the tollroad"
