messages_command:
  - ${simple_message_command}
  # - ${loop_message_command}

simple_message_command:
  - text: ${message_verb} ${recipient} ${message_exact_content}
    code: |
      ${recipient}
      ${message_exact_content}
      MessagesCommand.send_message(recipient=${recipient:var}, exact_content=${message_exact_content:var})

loop_message_command:
  - text: ${message_verb} ${contact.1}, ${contact.2} and ${contact.3} ${message_exact_content}
    code: |
      ${contact.1}
      ${contact.2}
      ${contact.3}
      for recipient in [${contact.1:var}, ${contact.2:var}, ${contact.3:var}]:
        ${message_exact_content}
        MessagesCommand.send_message(recipient=recipient, exact_content=${message_exact_content:var})

messages_query:
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender}
    code: |
      ${contact_i}
      ${sender}
      messages = MessagesQuery.get_messages(recipient=${contact_i:var}, sender=${sender:var})
      result = len(list(messages))
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender} {date_time_past}
    code: |
      ${contact_i}
      ${sender}
      ${date_time_past}
      messages = MessagesQuery.get_messages(recipient=${contact_i:var}, sender=${sender:var}, date_time=${date_time_past:var})
      result = len(list(messages))
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2}
    code: |
      ${contact_i}
      recipient = ${contact_i:var}
      ${sender.1}
      ${sender.2}
      result = True
      for sender in [${sender.1:var}, ${sender.2:var}]:
        messages = MessagesQuery.get_messages(recipient=recipient, sender=sender)
        result = result and len(list(messages))
    var: result
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2} {date_time_past}
    code: |
      ${contact_i}
      ${sender.1}
      ${sender.2}
      ${date_time_past}
      result = True
      for sender in [${sender.1:var}, ${sender.2:var}]:
        messages = MessagesQuery.get_messages(date_time=${date_time_past:var}, recipient=recipient, sender=sender)
        result = result and len(list(messages))
    var: result

message_verb:
  - text: text
  - text: tell

messages_possession_verb:
  - have
  - got

sender:
  - ${contact}

recipient:
  - text: ${contact}
    code: |
      ${contact}
      recipient = ${contact:var}
    var: recipient
    coreference_value:
      - value: him
        gend: masc
        num: sg
      - value: her
        gend: fem
        num: sg

message_exact_content:
  - text: ${message_exact_content_value}
    code: |
      ${message_exact_content:var} = Content.resolve_from_text("${message_exact_content_value}")
    var: exact_content

message_exact_content_value:
  - text: to meet us inside the restaurant
    code: "meet us inside the restaurant"
  - text: that I will be on time
    code: "I will be on time"
  - text: that I will be late
    code: "I will be late"
