messages_command:
  - ${simple_message_command}
  - ${loop_message_command}

simple_message_command:
  - text: ${message_verb} ${contact} ${message_exact_content}
    code: |
      ${contact}
      recipient = ${contact:var}
      ${message_exact_content}
      send_message(recipient=recipient, exact_content=${message_exact_content:var})

loop_message_command:
  - text: ${message_verb} ${contact.1}, ${contact.2} and ${contact.3} ${message_exact_content}
    code: |
      ${contact.1}
      ${contact.2}
      ${contact.3}
      for recipient in [${contact.1:var}, ${contact.2:var}, ${contact.3:var}]:
        ${message_exact_content}
        send_message(recipient=recipient, exact_content=${message_exact_content:var})

messages_query:
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender}
    code: |
      ${contact_i}
      ${sender}
      messages = messages.get_messages(recipient=${contact_i:var}, sender=${sender:var})
    var: messages
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender} {date_time_past}
    code: |
      ${contact_i}
      ${sender}
      ${date_time_past}
      messages = messages.get_messages(recipient=${contact_i:var}, sender=${sender:var}, date_time=${date_time_past:var})
    var: messages
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2}
    code: |
      ${contact_i}
      ${sender.1}
      ${sender.2}
      messages1 = messages.get_messages(recipient=${contact_i:var}, sender=${sender.1:var})
      messages2 = messages.get_messages(recipient=${contact_i:var}, sender=${sender.2:var})
      messages = messages1 + messages2
    var: messages
  - text: ${contact_i} ${messages_possession_verb} a message from ${sender.1} or ${sender.2} {date_time_past}
    code: |
      ${contact_i}
      ${sender.1}
      ${sender.2}
      ${date_time_past}
      messages1 = messages.get_messages(recipient=${contact_i:var}, sender=${sender.1:var}, date_time=${date_time_past:var})
      messages2 = messages.get_messages(recipient=${contact_i:var}, sender=${sender.2:var}, date_time=${date_time_past:var})
      messages = messages1 + messages2
    var: messages

message_verb:
  - text: text
  - text: tell

messages_possession_verb:
  - have
  - got

sender:
  - ${contact}

message_exact_content:
  - text: ${message_exact_content_value}
    code: |
      ${message_exact_content:var} = Content.resolve_from_text("${message_exact_content_value}")
    var: exact_content

message_exact_content_value:
  - text: to meet us inside the restaurant
    code: "meet us inside the restaurant"
  - text: that I will be on time
    code: "I will be on time"
  - text: that I will be late
    code: "I will be late"
