reminders_command:
  - ${reminders_create_command}
  - ${reminders_delete_command}

reminders_create_command:
  - text: ${remind_create_verb} ${contact_me} ${reminder_exact_content}
    code: |
      ${contact_me}
      person_reminded = ${contact_me:var}
      ${reminder_exact_content}
      RemindersCommand.create_reminder(person_reminded=person_reminded, exact_content=${reminder_exact_content:var})

reminders_delete_command:
  - text: ${remind_delete_verb} ${quantifier(reminders, det=the)} ${reminder_exact_content}
    code: |
      ${reminder_exact_content}
      reminders = RemindersQuery.get_reminders(exact_content=${reminder_exact_content:var})
      reminders = ${quantifier(reminders, det=the)}
      RemindersCommand.delete_reminder(reminders=reminders)
  - text: ${remind_delete_verb} ${quantifier(reminders, nmod:poss=$contact_my)} ${reminder_exact_content}
    code: |
      ${contact_my}
      person_reminded=${contact_my:var}
      ${reminder_exact_content}
      reminders = RemindersQuery.get_reminders(person_reminded=person_reminded, exact_content=${reminder_exact_content:var})
      reminders = ${quantifier(reminders, nmod:poss=$contact_my)}
      RemindersCommand.delete_reminder(reminders=reminders)

reminders_query:
  - text: ${contact_i} ${reminders_possion_verb} a reminder ${reminder_exact_content}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${reminder_exact_content}
      reminders = RemindersQuery.get_reminders(person_reminded=person_reminded, exact_content=${reminder_exact_content:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result
  - text: ${contact_i} ${reminders_possion_verb} a reminder ${reminder_date_time}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${date_time} 
      reminders = RemindersQuery.get_reminders(person_reminded=person_reminded, date_time=${date_time:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result
  - text: ${contact_i} ${reminders_possion_verb} a reminder ${reminder_date_time} ${reminder_exact_content}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${reminder_exact_content}
      reminders = RemindersQuery.get_reminders(person_reminded=person_reminded, date_time=${date_time:var}, exact_content=${reminder_exact_content:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result
  - text: ${contact_i} ${reminders_possion_verb} reminders ${reminder_exact_content}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${reminder_exact_content}
      reminders = reminders.get_reminders(person_reminded=person_reminded, exact_content=${reminder_exact_content:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result
  - text: ${contact_i} ${reminders_possion_verb} reminders ${reminder_date_time}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${date_time} 
      reminders = reminders.get_reminders(person_reminded=person_reminded, date_time=${date_time:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result
  - text: ${contact_i} ${reminders_possion_verb} reminders ${reminder_date_time} ${reminder_exact_content}
    code: |
      ${contact_i}
      person_reminded = ${contact_i:var}
      ${reminder_exact_content}
      reminders = reminders.get_reminders(person_reminded=person_reminded, date_time=${date_time:var}, exact_content=${reminder_exact_content:var})
      reminders_result = len(list(reminders)) > 0
    var: reminders_result

remind_create_verb:
  - remind
  - set a reminder for

remind_delete_verb:
  - remove
  - delete

reminders_possion_verb:
  - got
  - have

person_reminded:
  - text: from ${contact}
    code: ${contact}
    # var: ${contact:var}

reminder_exact_content:
  - text: ${reminder_exact_content_item}
    code: |
      ${reminder_exact_content:var} = Content.resolve_from_text("${reminder_exact_content_item}")
    var: exact_content

reminder_exact_content_item:
  - text: to bring a coat
    code: bring a coat
  - text: to leave 15 minutes earlier
    code: leave 15 minutes earlier

reminder_date_time:
  - text: for ${date_time}
    code: ${date_time}
    syn: PP 
